# Imagen base
FROM openzipkin/zipkin

# Puerto que usará Zipkin
EXPOSE 9411

CMD ["java", "-jar", "/zipkin.jar"]


#Esto no estaba en la documentacuión, debido a errores que sacaban los logs se añadió